### ISSUE TITLE
Umstellung der Buildstruktur für Maven/Tycho Hybridstruktur

### ISSUE THREAD

**Issue by hd42** [faktorips/faktorips.base#10]
Module, für die bisher eine nexus/pom.xml existiert sollten überarbeitet werden, so dass einheitliche Artefakte erstellt werden, die sowohl OSGi-Bundles und Maven-Artefakte sind.

**Comment by laeubi** [comment]
This is a relevant issue for this story, I'll take care to push this forward: 
- https://github.com/eclipse/tycho/pull/569

**Comment by hd42** [comment]
Bin gerade über den Artikel https://blog.frankel.ch/maven-flatten-plugin/ gestolpert. Vermutlich könnte das flatten-maven-plugin unsere /org.faktorips.p2repository/scripts/deployToMavenCentral.sh und nexus-poms/*.template ersetzen, so dass die veröffentlichten Artefakte nicht die ganzen Build-Konfigurationen im pom.xml haben.
