### ISSUE TITLE
de.faktorzehn.doc:jade-maven-plugin:1.0.2 is missing by faktorips-documentation

### ISSUE THREAD

**Issue by laeubi** [faktorips/faktorips.base#20]
`faktorips-documentation` references the plugin `de.faktorzehn.doc:jade-maven-plugin:1.0.2` but it is not part of the public repository and is not deployed on maven-central:

This makes the build fail with:

> [ERROR] Plugin de.faktorzehn.doc:jade-maven-plugin:1.0.2 or one of its dependencies could not be resolved: Could not find artifact de.faktorzehn.doc:jade-maven-plugin:jar:1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by hd42** [comment]
faktorips-documentation will be moved to a separate project for now.
