### ISSUE TITLE
Old babel-update-sites are no longer available

### ISSUE THREAD

**Issue by laeubi** [faktorips/faktorips.base#24]
The babel project archives their update-sites after a while. Faktorzehn is using only a small sub-set of the features, so I would recommend the following:

1. create a new github-repository (e.g. `faktorips.3rdparty`)
2. enable github pages for that repository
3. upload the required subset to that pages and let the public repository consume it from there

@hd42 could you setup 1+2 and I'll then provide a PR for 3 or you can add me with write access to the new repo.

**Comment by hd42** [comment]
@laeubi, you can now manage https://github.com/faktorips/faktorips.dependency.mirror
