### ISSUE TITLE
Use Class.getDeclaredConstructor().newInstance() instead of deprecated Class.newInstance

### ISSUE THREAD

**Issue by thake** [faktorips/faktorips.base#5]
Class.newInstance is deprecated since Java 9. The code generated by Faktor IPS still uses Class.newInstance (code: https://github.com/faktorips/faktorips.base/blob/96b1151fac9246165570febe7b4815d84cc9c5a7/org.faktorips.devtools.stdbuilder/src/org/faktorips/devtools/stdbuilder/xtend/policycmpt/template/PolicyCmptAssociationTmpl.xtend#L595). 

Please consider replacing it with a call to Class.getDeclaredConstructor().newInstance(). This call should be equivalent.

**Comment by hd42** [comment]
Thank you. This will be fixed in Faktor-IPS 21.6.

**Comment by hd42** [comment]
Fixed in FIPS-7042 / [b3ce0ae](https://github.com/faktorips/faktorips.base/commit/b3ce0aef55eef02acd525497d1d7b93adde3b088)
