### ISSUE TITLE
Add support to generate the "get*AnpStufe" with a parameter of type LocalDate instead of Calendar

### ISSUE THREAD

**Issue by thake** [faktorips/faktorips.base#7]
Currently I can't find any option to modify the IPS code generation in a way, so that the generated "get*AnpStufe" methods will be generated with a parameter of LocalDate instead of Calendar. 

My assumption was, that this can be achieved by setting the following property in the IpsArtefactBuilderSetConfig.
```xml
<Property name="localDateDatatypeHelperVariant" value="java8"/>
```
However, the methods will still be generated with a parameter of type Calendar.

Maybe it is even possible to drop Calendar support altogether as the Faktor-IPS runtime already requires Java 8.

**Comment by hd42** [comment]
The localDateDatatypeHelperVariant only configures whether LocalDate/Time datatypes are used from joda time or Java 8+. The API for Anpassungsstufen still uses the much older Calendar for backwards compatibility, as it was created for Java 1.4 originally.
If you have access to the f10-commons packages, de.faktorzehn.commons.util.LocalDateUtil#toCalendar(LocalDate) can be used to convert LocalDates to GregorianCalendar instances.
