### ISSUE TITLE
Umbau der Targets

### ISSUE THREAD

**Issue by hd42** [faktorips/faktorips.base#9]
- statt einer eigenen Updatesite (thirdparty) direkt Maven-Dependencies
- evtl. kann man die Gemeinsamkeiten der diversen Targets (1 je Eclipse-Version die wir unterstützen) rausziehen und einfacher verwalten?

**Comment by laeubi** [comment]
@hd42 Habt ihr irgendwo eine Liste / Target / Maven build /... wo aufgelistet ist welche externen Abhängigkeiten derzeit in eine eigene Updatesite gepackt werden? Sind diese alle obligatorisch oder ist da mehr drinne al für Faktor ips benötigt wird?

**Comment by hd42** [comment]
@laeubi: siehe Mail

**Comment by laeubi** [comment]
Dies sit nun erledigt:

1. thirdparty sind maven dependecies
2. diese sind in ein allgemeines target ausgelagert was von allen verwendet wird
3. matrix build für GH actions ist eingerichtet
